config/routes.rb
Rails.application.routes.draw do
  root 'sudoku#index'
  post 'sudoku/index'
  get 'sudoku/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sudoku_controller.rb
class SudokuController < ApplicationController
  def index
    @solution = Array.new(9) { Array.new(9, 0) }
    if request.post?
      @sudoku = params[:sudoku].to_unsafe_h.values.map { |row| row.values.map(&:to_i) }
      if params.keys.include? 'solve'
        @solved_sudoku = solve_sudoku(@sudoku)
        if !@solved_sudoku
          @solution = @sudoku
          @cantSolve = true
        elsif @solved_sudoku == true
          @solution = @sudoku
        else
          @solution = @solved_sudoku
        end
      else
        @solution = @sudoku
        @isSolved = sudoku_solved?(@sudoku)
      end
    end
  end

  private

def solve_sudoku(grid)
    find = find_empty_cell(grid)
    return true if !find
  
    row, col = find
  
    (1..9).each do |num|
      if valid?(grid, row, col, num)
        grid[row][col] = num
  
        if solve_sudoku(grid)
          return grid
        end
        grid[row][col] = 0
      end
    end

    return false
  end
  
  def find_empty_cell(grid)
    grid.each_with_index do |row, i|
      row.each_with_index do |cell, j|
        if cell == 0
          return [i, j]
        end
      end
    end
    return nil
  end

  def valid?(grid, row, col, num)
    for i in 0..8
      if grid[row][i] == num
        return false
      end
    end
  
    for i in 0..8
      if grid[i][col] == num
        return false
      end
    end
  
    box_row = (row / 3) * 3
    box_col = (col / 3) * 3
    for i in 0..2
      for j in 0..2
        if grid[box_row + i][box_col + j] == num
          return false
        end
      end
    end
  
    return true
  end

  def sudoku_solved?(grid)
    for row in 0..8
      if !valid_group?(grid[row])
        return 0
      end
    end
  
    for col in 0..8
      if !valid_group?(grid.map { |row| row[col] })
        return 0
      end
    end
  
    for box_row in 0..2
      for box_col in 0..2
        box = []
        for row in 0..2
          for col in 0..2
            box << grid[box_row * 3 + row][box_col * 3 + col]
          end
        end
        if !valid_group?(box)
          return 0
        end
      end
    end
  
    return 1
  end
  
  def valid_group?(group)
    return group.sort == (1..9).to_a
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sudoku_helper.rb
module SudokuHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SudokuSolver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sudoku/index.html.erb
<h1>Введіть судоку</h1>

<%= form_with url: sudoku_index_path, method: :post, local: true, data: { turbo: false } do |form| %>
  <table>
    <% 9.times do |row| %>
      <tr>
        <% 9.times do |col| %>
          <td>
            <%= form.number_field "sudoku[#{row}][#{col}]", min: 0, max: 9, class: "sudoku-input", value: @solution[row][col] %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= button_tag "Рандом", type: "button", id: "randomize" %>
  <%= form.submit "Вирішити", name: "solve" %>
  <%= form.submit "Перевірити", name: "check" %>
<% end %>

<% if @isSolved.present? %>
  <% if @isSolved == 1 %>
    <p>Судоку вирішено вірно!</p>
  <% else %>
    <p>Судоку вирішено не вірно!</p>
  <% end %>
<% end %>

<% if @cantSolve.present? %>
  <p>Немає рішень!</p>
<% end %>